version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=$AWS_DEFAULT_REGION
      - ECR_REGISTRY=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  build:
    commands:
      - echo Build started on `date`
      
      - echo Building Web Docker image...
      - docker build -t $ECR_REGISTRY/web:latest ./web
      
      - echo Building API Docker image...
      - docker build -t $ECR_REGISTRY/api:latest ./api

  post_build:
    commands:
      - echo Pushing Web image...
      - docker push $ECR_REGISTRY/web:latest
      
      - echo Pushing API image...
      - docker push $ECR_REGISTRY/api:latest
      
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'